### ISSUE TITLE
文本语义匹配搜索

### ISSUE THREAD

**Issue by 1264561652** [shibing624/similarities#10]
文本语义匹配搜索那个示例中 为什么每次都from similarities import Similarity这一句运行不过去？是我需要下载什么模型到本地吗

**Comment by shibing624** [comment]
需要下载中文相似匹配模型：https://huggingface.co/shibing624/text2vec-base-chinese

```
class Similarity(SimilarityABC):
    """
    Sentence Similarity:
    1. Compute the similarity between two sentences
    2. Retrieves most similar sentence of a query against a corpus of documents.

    The index supports adding new documents dynamically.
    """

    def __init__(
            self,
            corpus: Union[List[str], Dict[str, str]] = None,
            model_name_or_path="shibing624/text2vec-base-chinese",
            encoder_type="MEAN",
            max_seq_length=128,
            device=None,
    )

```

下载好模型后，把模型目录传给`model_name_or_path`

**Comment by 1264561652** [comment]
对，是下载了这么改路径的操作之后，但还是同样的报错，这个该如何解决？





---- 回复的原邮件 ----
| 发件人 | Ming Xu ***@***.***> |
| 日期 | 2023年06月05日 20:35 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [shibing624/similarities] 文本语义匹配搜索 (Issue #10) |

需要下载中文相似匹配模型：https://huggingface.co/shibing624/text2vec-base-chinese

class Similarity(SimilarityABC):
    """
    Sentence Similarity:
    1. Compute the similarity between two sentences
    2. Retrieves most similar sentence of a query against a corpus of documents.

    The index supports adding new documents dynamically.
    """

    def __init__(
            self,
            corpus: Union[List[str], Dict[str, str]] = None,
            model_name_or_path="shibing624/text2vec-base-chinese",
            encoder_type="MEAN",
            max_seq_length=128,
            device=None,
    )



下载好模型后，把模型目录传给model_name_or_path

**Comment by shibing624** [comment]
啥错？
