### ISSUE TITLE
本项目实现检索、召回的底层原理是什么？

### ISSUE THREAD

**Issue by geolvr** [shibing624/similarities#12]
例如，一种主流的方法是依赖向量数据库(如faiss, milvus等)存储embedding，然后用向量数据库自身提供的方法实现topk相似样本召回。
请问本项目实现检索、召回topk相似样本的实现机理是什么？

**Comment by shibing624** [comment]
Hnsw 和 annoy检索

**Comment by shibing624** [comment]
+ faiss.
