### ISSUE TITLE
增加清空corpus

### ISSUE THREAD

**Issue by lifeitech** [shibing624/similarities#13]
既然能`add_corpus`，那么也应该implement删除某个corpus，以及清空所有corpus。

**Comment by shibing624** [comment]
加到todo，优先级较低。

**Comment by qichengzx** [comment]
> 加到todo，优先级较低。

没有看到相关的清空corpus的方法呢？提交记录也没有看到跟当前issue有关的commit

**Comment by shibing624** [comment]
corpus是个dict，删除时使用del就可以，清空用corpus = {} 重置就行，不纳入开发中，用户自行处理就好。
```python
my_dict = {'a': 1, 'b': 2, 'c': 3}

# 删除键是 'b' 的条目
del my_dict['b']

print(my_dict)  # 将显示 {'a': 1, 'c': 3}
```
