### ISSUE TITLE
Similarity可以动态的更新corpus吗

### ISSUE THREAD

**Issue by xxyp** [shibing624/similarities#14]
初始化的时候已经执行过add corpus了，后续如果有文档新增，可以直接再全量add吗，全量add会不会和之前的重复，有没有什么比较好的动态更新方法呢

**Comment by shibing624** [comment]
全量add不会和之前的重复，会自动过滤，库里有的不会新增

**Comment by xxyp** [comment]
嗯嗯好的，谢谢~
