### ISSUE TITLE
您好，在huggingface看到有text2vec-base-chinese的ONNX导出部署模型，请问有相关部署流程参考，学习一下谢谢。

### ISSUE THREAD

**Issue by dingidng** [shibing624/similarities#16]
[shibing624/text2vec-base-chinese](https://huggingface.co/shibing624/text2vec-base-chinese)

您好，在huggingface看到有text2vec-base-chinese的ONNX导出部署模型，请问有相关部署流程参考，学习一下谢谢。

**Comment by shibing624** [comment]
fellow https://github.com/onnx/tutorials
