### ISSUE TITLE
导入模块失败

### ISSUE THREAD

**Issue by cliweichen** [shibing624/similarities#17]
File ~/miniconda3/lib/python3.8/site-packages/aiohttp/client_reqrep.py:72
     70     import cchardet as chardet
     71 except ImportError:  # pragma: no cover
---> 72     import charset_normalizer as chardet  # type: ignore[no-redef]
     75 __all__ = ("ClientRequest", "ClientResponse", "RequestInfo", "Fingerprint")
     78 if TYPE_CHECKING:  # pragma: no cover

File ~/miniconda3/lib/python3.8/site-packages/charset_normalizer/__init__.py:23
      1 """
      2 Charset-Normalizer
      3 ~~~~~~~~~~~~~~
   (...)
     21 :license: MIT, see LICENSE for more details.
     22 """
---> 23 from charset_normalizer.api import from_fp, from_path, from_bytes, normalize
     24 from charset_normalizer.legacy import detect
     25 from charset_normalizer.version import __version__, VERSION

File ~/miniconda3/lib/python3.8/site-packages/charset_normalizer/api.py:10
      7     PathLike = Union[str, 'os.PathLike[str]']  # type: ignore
      9 from charset_normalizer.constant import TOO_SMALL_SEQUENCE, TOO_BIG_SEQUENCE, IANA_SUPPORTED
---> 10 from charset_normalizer.md import mess_ratio
     11 from charset_normalizer.models import CharsetMatches, CharsetMatch
     12 from warnings import warn

AttributeError: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)

**Comment by shibing624** [comment]
cc https://github.com/howie6879/magic_google/issues/13
