### ISSUE TITLE
计算图片相似度image_demo报错

### ISSUE THREAD

**Issue by Gxy-2001** [shibing624/similarities#2]
### Describe the bug
安装好环境后，运行计算图片相似度image_demo时报错，截图如下 (前面计算文本相似度正常  

Pillow 版本 9.0.1，image版本1.5.33  尝试换过几个pillow，但还是报错

谢谢作者！

![pic](https://user-images.githubusercontent.com/56917631/158377544-23065471-f7ef-4eea-a5ce-8f27e3166cec.jpg)

**Comment by shibing624** [comment]
更新到最新版源码，跑example的image demo。

**Comment by Gxy-2001** [comment]
> 

就是今天下载的源码，跑的就是examples里的demo

**Comment by shibing624** [comment]
pip install similarities==1.0.1

**Comment by Gxy-2001** [comment]
谢谢回复！
刚看了下我用`pip3 install -U`下载的版本是1.0.0的，几次重复都是1.0.0
更新到1.0.1确实没有这个问题了
谢谢你
