### ISSUE TITLE
如何创建增量索引？

### ISSUE THREAD

**Issue by JiejieDeng** [shibing624/similarities#20]
尤其是面对百万级和千万级图片创建索引的场景
1. 图片是分布式存储的
2. 每次都重头开始生成索引，时间太长了
请指教！

**Comment by shibing624** [comment]
新增的，新建文件补在后面，比如00010.npy， 00011.npy等，索引里面顺序加载一遍就可以，faiss重新load

**Comment by JiejieDeng** [comment]
已测试通过，非常感谢！

只不过corpus目录下的文件也需要这样不同的数据集进行处理调用clip_embedding方法之后，必须修改文件名称part-00000.parquet。
如第一个数据集part-00000.parquet，第二个数据集part-00001.parquet；image_emb目录下同上述操作。
ll clip_engine/
drwxr-xr-x 2 root root 4096 11月  8 17:46 corpus
drwxr-xr-x 2 root root 4096 11月  8 17:46 image_emb

**Comment by shibing624** [comment]
嗯。
