### ISSUE TITLE
clip_embedding的时候我想换成英文模型而非中文，请问使用OFA-sys的哪一个英文模型呢？

### ISSUE THREAD

**Issue by JiejieDeng** [shibing624/similarities#23]
你好，我测试了中文模型搜索的结果非常好，model_name="OFA-Sys/chinese-clip-vit-base-patch16",

但是翻译成英文之后，搜索结果不理想，我的多语言需求需要我完成英文方面的图片搜索和推荐，

请问我在clip_embedding的时候，使用OFA-sys的哪一个英文模型呢？

https://huggingface.co/OFA-Sys

**Comment by shibing624** [comment]
英文的不要用ofa的，ofa是阿里开源的，用openai的就行，https://huggingface.co/openai/clip-vit-base-patch32

**Comment by JiejieDeng** [comment]
好的，我直接用openai的模型替换之前中文的。
谢谢~
