### ISSUE TITLE
AttributeError: module 'cv2.cv2' has no attribute 'SIFT_create'

### ISSUE THREAD

**Issue by EASTERNTIGER** [shibing624/similarities#24]
老师您好，我在试运行image_semantic_search_demo.py 时报错：AttributeError: module 'cv2.cv2' has no attribute 'SIFT_create'。将image_similarity.py 中line152由self.sift = cv2.SIFT_create(nfeatures=nfeatures) 改为 self.sift = cv2.xfeatures2d.SIFT_create(nfeatures=nfeatures)后报错：AttributeError: module 'cv2.cv2' has no attribute 'xfeatures2d'  请问这个问题该怎么解决呢？
python=3.7.16 
opencv-python=4.2.0.32
opencv-contrib-python=4.6.0.66
需要将python降版本吗

**Comment by shibing624** [comment]
我本地是python3.10， 
```
opencv-contrib-python                        4.6.0.66
opencv-python                                4.6.0.66
opencv-python-headless                       4.7.0.72
```
