### ISSUE TITLE
ANTIALIAS 已经被弃用

### ISSUE THREAD

**Issue by qichengzx** [shibing624/similarities#26]
### Describe the bug

AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

### To Reproduce

python3 image_semantic_search_demo.py

### Context
 - **Python** Python3.11

### Additional Information

是否应该替换成LANCZOS

**Comment by shibing624** [comment]
还没在python3.11测试，py3.8 -- py3.10均可。
