### ISSUE TITLE
AutoTokenizer冲突

### ISSUE THREAD

**Issue by Und3r1ine** [shibing624/similarities#27]
### Describe the Question
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.modelscope.cn/api/v1/models/shibing624/text2vec-base-chinese/revisions

使用的代码
```
from similarities import BertSimilarity
import modelscope
tokenizer = modelscope.AutoTokenizer.from_pretrained(model_dir,local_files_only=True,trust_remote_code=True)
model = modelscope.AutoModel.from_pretrained(model_dir,local_files_only=True,trust_remote_code=True).half().cuda()
```

**Comment by Und3r1ine** [comment]
可能是similarities使用的是transformers,我把modelscope换成transformers，就不存在冲突了

**Comment by shibing624** [comment]
嗯
