### ISSUE TITLE
处理文件格式是否可以增加webp格式？

### ISSUE THREAD

**Issue by JiejieDeng** [shibing624/similarities#32]
文件  site-packages/similarities/faiss_clip_similarity.py中只能支持".png", ".jpg", ".jpeg", ".bmp"这些图片格式，

请问是否可以快速扩展，然后支持webp格式呢？

def preprocess_image(image_input: Union[str, np.ndarray, bytes]) -> Image.Image:
    """
    Process image input to Image.Image object
    """
    if isinstance(image_input, str):
        if not os.path.isfile(image_input):
            print(image_input)
            return image_input
        if image_input.startswith('http'):
            return Image.open(requests.get(image_input, stream=True).raw)
        elif image_input.endswith((".png", ".jpg", ".jpeg", ".bmp")) and os.path.isfile(image_input):
            return Image.open(image_input)
        else:
            raise ValueError("Unsupported image input type")
    elif isinstance(image_input, np.ndarray):
        return Image.fromarray(image_input)
    elif isinstance(image_input, bytes):
        img_data = base64.b64decode(image_input)
        return Image.open(BytesIO(img_data))
    else:
        raise ValueError("Unsupported image input type")

**Comment by shibing624** [comment]
fixed。 https://github.com/shibing624/similarities/commit/f7799eaffd24a727033299caea3f4cb00a1f8cf9
