### ISSUE TITLE
BM25Similarity、TfidfSimilarity的add_corpus导致语料乱序

### ISSUE THREAD

**Issue by zhangmianhongni** [shibing624/similarities#34]
BM25Similarity、TfidfSimilarity的add_corpus导致语料乱序

    def add_corpus(self, corpus: Union[List[str], Dict[int, str]]):
        """
        Extend the corpus with new documents.

        Parameters
        ----------
        corpus : dict
        """
        corpus_new = {}
        start_id = len(self.corpus) if self.corpus else 0
        if isinstance(corpus, list):
            **corpus = list(set(corpus))**
            for id, doc in enumerate(corpus):
                if doc not in list(self.corpus.values()):
                    corpus_new[start_id + id] = doc
        else:
            for id, doc in corpus.items():
                if doc not in list(self.corpus.values()):
                    corpus_new[id] = doc
        self.corpus.update(corpus_new)

        logger.info(f"Start computing corpus embeddings, new docs: {len(corpus_new)}")
        corpus_texts = list(self.corpus.values())
        corpus_seg = [jieba.lcut(d) for d in corpus_texts]
        corpus_seg = [[w for w in doc if (w.strip().lower() not in self.default_stopwords) and
                       len(w.strip()) > 0] for doc in corpus_seg]
        self.bm25 = BM25Okapi(corpus_seg)
        logger.info(f"Add {len(corpus)} docs, total: {len(self.corpus)}")

corpus = list(set(corpus))这句话导致BM25Similarity的corpus的顺序跟原来顺序不一致，然后如果使用EnsembleSimilarity的most_similar时候，由于BertSimilarity的corpus是正常的顺序，BM25Similarity的corpus顺序又是另外一个顺序，most_similar出来的得分加成计算会有错误，因为doc_id不一致的原因导致同一个语料在2个模型中的得分在求和的时候是错的。

**Comment by shibing624** [comment]
fixed.
