### ISSUE TITLE
ImportError: cannot import name 'Literal' from 'typing' 求解

### ISSUE THREAD

**Issue by py-syy** [shibing624/similarities#44]
python3.7.4 
运行此代码报错：ImportError: cannot import name 'Literal' from 'typing' 求解

`from similarities import BertSimilarity
    m = BertSimilarity(model_name_or_path=r"D:\Work\python_project\model\text2vec-base-chinese")
    r = m.similarity('如何更换花呗绑定银行卡', '花呗更改绑定银行卡')
    print(f"similarity score: {float(r)}") v`

**Comment by shibing624** [comment]
用python3.10

**Comment by py-syy** [comment]
ok
