### ISSUE TITLE
ann预测速度那么慢，比原生模型慢很多？

### ISSUE THREAD

**Issue by song4875343** [shibing624/similarities#5]
首先为你的模型点赞，我感觉开源的中文模型，除了百度的rocketqa模型你的模型准确度最高。有两个问题请教你
为啥你例子中的ann速度那么慢，如果直接用你的模型而用sentence transform速度却是你的几分之一，包括模型调入和导库。
另外还有一个问题用同样一个模型，用ann的准确度为啥比一般的差很多，是我使用的问题还是两者原理的差别。
渴望你的解答

**Comment by shibing624** [comment]
1. ann检索是有损的最近邻召回向量检索，速度是肯定比原生用模型快的，我这边测试相同环境下，也是ann比原生模型预测速度快3-4倍；
2. ann检索需要先构建索引文件，这个比较耗时，属于预处理，可以离线做，所以不算到预测耗时中，计算耗时要把m.add_corpus(corpus_new)、m.build_index() 的耗时排除；
3. ann既然是有损检索，准确率肯定会有损失，海量数据下准确率下降应该不会差很多，我测试一般差5%以内的。

**Comment by song4875343** [comment]
另外一个问题，我是想表达的是，用你的模型ann召回的第一个结果命中率很高，其他相关性较差。而我用paddle的rocketqa 召回，前面几个相关性都不错，另外你的模型的相似度比较却很不错，一般情况ann召回50个命中率已经非常高了，另外我用的是faiss的L2搜索，应该是精确计算。我比较迷惑所以才提问的。

**Comment by shibing624** [comment]
1. quick_sentence_transformers比原生sbert模型快的原因是用了onnx+tensorrt推理加速，这个是gpu模型部署上线的常用操作，你也可以参考；
2. 你用faiss算向量余弦相似度，用IndexFlatIP试试
3. paddle的rocketqa我不清楚，你自行调研哪个好用哪个就行，都是开源的，也可以自己改模型。

**Comment by song4875343** [comment]
非常感谢
