### ISSUE TITLE
你好，我想问下为什么我在本地windows上使用ClipSimilarity计算两张图片的相似度只要0.2s左右，但是同样的代码在linux上却需要2s-3s呢

### ISSUE THREAD

**Issue by AI-Candy-Yang** [shibing624/similarities#7]
- [ ] I checked to make sure that this is not a duplicate issue
- [ ] I'm submitting the request to the correct repository (for model requests

### Additional Information
Other things you want the developers to know.

**Comment by AI-Candy-Yang** [comment]
我们没有gpu，在cpu上跑的

**Comment by shibing624** [comment]
看下计算结果是否一样，如果一样，证明模型是ok的，那大概是win的电脑配置比linux的配置高，具体是cpu、内存、ssd
